### ISSUE TITLE
Update/Move elevation indicator from map

### ISSUE THREAD

**Issue by charlieboygis** [MrMufflon/Leaflet.Elevation#14]
First, thank you for this nice and useful control.
It would be great to update the control indicator moving over or clicking on the map feature (that is, the opposite behavior of how is working the control now...)
I would like to try to implement that feature but I don't know D3. I think I would need a function to convert from an altitude (obtained from the element on the data array with latlng equal or near the latlng of the mouse position when hovering or clicking on the map) to the position on the control container...
Can you give some hints?

**Comment by MrMufflon** [comment]
This was solved with f5cdc1438602d102481e23f069f06d67dc04850f and is available in the latest version
