### ISSUE TITLE
Hover over track and see where you are on elevation profile

### ISSUE THREAD

**Issue by bouton** [MrMufflon/Leaflet.Elevation#22]
Currently if you hover over the elevation profile you see where you are on the track on the map (very nicely I might add) bit it would be nice if it also worked in reverse, ie you hover over track position and it is marked on the elevation profile where you are.

Thanks again for your hard work. I am experimenting using this is a wordpress plugin.

**Comment by MrMufflon** [comment]
Fixed with f5cdc1438602d102481e23f069f06d67dc04850f
