### ISSUE TITLE
Different profile for each feature in GeoJSON file

### ISSUE THREAD

**Issue by pufanalexandru** [MrMufflon/Leaflet.Elevation#28]
Hello, and congratulations for your good work with this plugin.

I wonder if there is any way to get a different profile for each line from a GeoJSON file. I currently have two different profiles, but they appear when the map is loaded instead of when a feature is clicked. Is there a better way to achieve this? Here's a JSFiddle of my work: http://jsfiddle.net/pufanalexandru/eaok0Lnz/4/

Thanks!

**Comment by MrMufflon** [comment]
Thanks!
There is currently no better way to achieve multiple profiles than to add a new control for each dataset.

**Comment by LucaMoiana** [comment]
here is what I came up with: http://lucamoiana.github.io/maggiore/
Now I'd like to style profiles with different css, how do I do? If I set different themes they are used right just the first time, then it uses the same.

**Comment by MrMufflon** [comment]
Looks nice! 
You mean two different themes at the same time? That´s not possible with the ways the theme selectors work. The theme-identifier is appended to the body dom node as the profile is initialized. So the first profile to be launched should have the correct theming. The second one then overrides the first one. This means that the CSS selector wins which was evaluated last, respectively standing last in the CSS file.
To make this work the code needs to be changed to append the theme selector only to the according control dom node.
