### ISSUE TITLE
jasmine -> jasmine-core

### ISSUE THREAD

**Issue by LeOSW42** [MrMufflon/Leaflet.Elevation#31]
Hello again,

You need to replace jasmine by jasmine-core here :
https://github.com/MrMufflon/Leaflet.Elevation/blob/master/package.json#L18

Léo

**Comment by MrMufflon** [comment]
Thanks, but just the pivotal changed to jasmine...
fb120ed1eed5dd9a236722b973ded8f0d7b7a6eb
