### ISSUE TITLE
"Uncaught TypeError: Cannot read property 'on' of undefined" on example_gpx.html

### ISSUE THREAD

**Issue by jbcoder** [MrMufflon/Leaflet.Elevation#34]
I'm testing this out on my dev server. All I've done is copied the files over and tried running the example_gpx.html file. I'm getting the error this error.

L.Control.Elevation.L.Control.extend.addData	@	Leaflet.Elevation-0.0.2.min.js:2
(anonymous function)	@	example_gpx.html:49
o.Mixin.Events.fireEvent	@	leaflet.js:6
L.GPX.L.FeatureGroup.extend._parse_gpx_data	@	gpx.js:276
cb	@	gpx.js:249
req.onreadystatechange	@	gpx.js:241

**Comment by MrMufflon** [comment]
Thanks, fixed in 5a471ca
