### ISSUE TITLE
Chart outside the map

### ISSUE THREAD

**Issue by tosolini** [MrMufflon/Leaflet.Elevation#36]
Hi MrMufflon, there is a way to show the chart outside the map? I'm using a small map on webpage, and would be nice show the elevation chart below and not on it. thx.

**Comment by MrMufflon** [comment]
Hi, not naturally, but here´s a workaround: https://github.com/MrMufflon/Leaflet.Elevation/issues/7

**Comment by tosolini** [comment]
Hi, thx for the trip. It works :)
