### ISSUE TITLE
elevation.png path is hardcoded

### ISSUE THREAD

**Issue by toverux** [MrMufflon/Leaflet.Elevation#37]
Hello,

The path to the only image you use in the lib is hardcoded in the LESS file as `"images/elevation.png"`.
I think it could be more useful to let the user choose the path *via* an option in the `L.control.elevation` constructor. Theoretically and aesthetically, it is actually better in the CSS, but have a thought for the people who just use your dist files or the (outdated !) Bower package without a complex compilation toolchain for all the dependencies.
So just now, I have to add one more task to my Grunt just for Leaflet.Elevation LESS file...

In any case, thanks for your lib, it is efficient and simple to use :)

**Comment by MrMufflon** [comment]
Hi,

that's actually true. But I'd rather add an optional config parameter that changes the buttons CSS class from `elevation-toggle` to anything else. This way the you have full control over it.
Added in 26b7548017d9bc2e9c997420e7aec21c4d3d493f
