### ISSUE TITLE
can you treat the control as a layer?

### ISSUE THREAD

**Issue by kas84** [MrMufflon/Leaflet.Elevation#40]
It should be a layer since you may want to hide it.

**Comment by kas84** [comment]
I've found a hacky solution that works for me... override onAdd and onRemove methods to show and hide elevation div

```
        var gjl = L.geoJson(altitude_layer,{
            onEachFeature: el.addData.bind(el)
        }).addTo(map);
        gjl.onRemove=function (t){
            $(".elevation").hide();
            this.eachLayer(t.removeLayer,t),this._map=null
        };
        gjl.onAdd=function (t){
            $(".elevation").show();
            this._map=t,this.eachLayer(t.addLayer,t);
        };
```

**Comment by kas84** [comment]
I think it's beyond the scope of this plugin but...

Would be great if instead of a Control the elevation was another layer you position on the map, since you could have many elevations you want to checkout on a map.

Think of a map of the "Tour de France" stages where you want to see an elevation map of each stage.

**Comment by MrMufflon** [comment]
I also think this is out of scope. 
You can still achieve this by writing a controller that sets the current data on the elevation control.
