### ISSUE TITLE
Format Elevation at Tooltip

### ISSUE THREAD

**Issue by dret** [MrMufflon/Leaflet.Elevation#44]
when setting the elevation formatting to 2 decimals, this is taken into account for the graph, but not for the tooltip that is following the line. this still displays elevation in full resolution (which often is way too much). it would be great to apply he formatting function to the tooltip as well.

**Comment by MrMufflon** [comment]
Hi,
if I set the hovernumber accordingly it formats both to two decimals
` hoverNumber: {
            decimalsX: 3,
            decimalsY: 2
        },`

Can you provide a sample?

**Comment by dret** [comment]
thanks for the feedback! this [screen shot](https://cloud.githubusercontent.com/assets/1848612/13488599/896f865e-e122-11e5-88be-4f382e2c7546.png) shows the problem, and here's the config i am using:

```javascript
hoverNumber: {
  decimalsX: 2, 
  decimalsY: 0, 
  formatter: undefined 
}
```

i am not sure where the `formatter` is coming from, i guess i just copied this from somewhere. is it possible that the formatter is the problem?

**Comment by MrMufflon** [comment]
The "decimalsY" attribute is used for the height labels. So setting it to 2 should round your numbers as you wish. The formatter attribute can be deleted if you don´t specify a formatting function.

**Comment by dret** [comment]
it works for the graph tooltip, but not for the line tooltip, as you can see in the screen shot. i am not sure if that's a bug, or a missing feature.

**Comment by MrMufflon** [comment]
But your example states decimalsY=0 not 2. Or do you want to have no decimals at all?

**Comment by dret** [comment]
On 2016-03-03 11:17 , Felix Bache wrote:
> But your example states decimalsY=0 not 2. Or do you want to have no
> decimals at all?

i am fine with how it shows up on the graph: two decimals for distance, 
none for elevation. what i was hoping for that it also would show up 
like this (no decimals, and not full precision as it is now) on the 
pointer on the line.

**Comment by MrMufflon** [comment]
With the latest version this works fine for me.
![screenshot from 2016-03-03 19-23-45](https://cloud.githubusercontent.com/assets/4553186/13504860/9bd8e5b6-e176-11e5-81eb-adcbbbe28117.jpg)

**Comment by dret** [comment]
On 2016-03-03 19:32 , Felix Bache wrote:
> With the latest version this works fine for me.

i have to admit that i was using 0.0.2 so far. however, now i am trying 
to switch to 0.0.4, but when simply switching the JS and CSS files, 
things stop working completely. i don't even see my track anymore, let 
alone the elevation graph. i guess i have to spend some time to try to 
figure out how to upgrade from 0.0.2 to 0.0.4, or is there anything that 
comes to mind that could be a problem?

**Comment by dret** [comment]
figured out my upgrade issues and on this new [screen shot](https://cloud.githubusercontent.com/assets/1848612/13510287/23d229a0-e190-11e5-90b2-ff337be3c1dc.png), it indeed works. i should have looked at the version i am using. thanks for the feedback and help!

**Comment by MrMufflon** [comment]
Great to hear it works now!
